"""Generate (query, passage, label) training data from the policy corpus.

    python -m training.build_pairs --dry-run --limit 3     # read these first
    python -m training.build_pairs --provider deepseek

Fine-tuning needs hundreds of labelled pairs; the eval set has 30 cases. So the
queries are synthetic — a model writes the questions an analyst would ask of each
clause — and the labels come from the corpus structure rather than from judgement:
the source chunk is the positive, and the **hard negatives are mined from the
retriever's own top hits for that query**, which is what makes them hard. Random
negatives are trivially separable and produce near-zero gradient.

Two rules that decide whether this is a measurement or a leak:

- **Split by document, never by query.** Queries generated from the same chunk are
  near-duplicates; scattering them across train and test means memorising the
  train half answers the test half. `training/train_rerank.py` does the split.
- **Never generate from the eval queries.** Those are dispute narratives in
  seed.py, structurally unlike these questions, and they are the held-out signal.

Generation is the step most likely to be silently bad, so every row records which
provider and prompt produced it, and `--dry-run` prints samples before you spend.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from agent.providers import KINDS, get_provider
from server.retrieval import Chunk, get_retriever, load_corpus

OUT = Path(__file__).parent.parent / "data" / "train_pairs.jsonl"

# Bumped when the wording changes, so rows generated by different prompts are
# never silently mixed in one training set.
PROMPT_VERSION = 1

PROMPT = """You are writing search queries for a bank's dispute-triage system.

Below is one clause from the bank's policy manual. Write {n} SHORT search queries
that a dispute analyst would type to find THIS clause, given a real case in front
of them.

Each query must read like a CASE, not like a topic. Include concrete facts: the
account type, the amount, how many days since the statement, prior claim count,
account standing.

GOOD (this is the shape the real agent produces):
  debit account, unauthorised dispute, disputed amount 842.50, 0 prior claims in 12 months, account status active
  atm dispute, debit account, machine debited 300 and dispensed 200, reported next day
BAD (topic labels — useless, these match everything):
  debit card dispute
  Regulation E dispute

Rules:
- Do NOT quote or paraphrase the clause text. A query that restates the clause
  measures nothing — the retriever would be matching itself.
- Do NOT mention the policy id.
- Vary the amounts, dates and account details between queries.
- One query per line. No numbering, no bullets, no commentary.

Clause:
{text}
"""

# Minimum words for a query to count as a case rather than a topic label. The
# first generator run produced "debit card dispute" and "Regulation E dispute" —
# short, generic, and *not* caught by the verbatim filter, because being generic
# is the opposite failure from being too close to the source. Training on them
# would teach the reranker to match topics while the agent asks in case facts.
MIN_QUERY_WORDS = 7


@dataclass(frozen=True)
class Pair:
    query: str
    passage: str
    label: int  # 1 positive, 0 hard negative
    policy_id: str  # the document the PASSAGE belongs to (split key)
    query_policy_id: str  # the document the QUERY was generated from
    heading: str
    provider: str
    model: str
    prompt_version: int


def looks_like_the_clause(query: str, chunk: Chunk) -> bool:
    """Reject queries that just restate the source.

    A near-verbatim query makes retrieval trivially perfect and teaches the model
    nothing. Cheap proxy: heavy token overlap with the chunk's own wording.
    """
    q = set(re.findall(r"[a-z0-9]+", query.lower()))
    c = set(re.findall(r"[a-z0-9]+", chunk.text.lower()))
    if not q:
        return True
    return len(q & c) / len(q) > 0.85


def too_generic(query: str) -> bool:
    """Reject topic labels like 'debit card dispute'.

    The opposite failure from `looks_like_the_clause`, and not caught by it: a
    short generic query has *low* overlap with the source. It matches half the
    corpus, so it teaches the reranker nothing and does not resemble what the
    agent actually sends.
    """
    return len(re.findall(r"[a-z0-9]+", query.lower())) < MIN_QUERY_WORDS


async def generate_queries(chunk: Chunk, provider: Any, n: int) -> list[str]:
    reply = await provider.client.chat.completions.create(
        model=provider.model,
        messages=[{"role": "user", "content": PROMPT.format(n=n, text=chunk.text[:1500])}],
        temperature=0.8,
    )
    text = reply.choices[0].message.content or ""
    out = []
    for line in text.splitlines():
        line = re.sub(r"^\s*(?:[-*•]|\d+[.)])\s*", "", line).strip().strip('"')
        if 15 < len(line) < 300:
            out.append(line)
    return out[:n]


def mine_negatives(query: str, source: Chunk, retriever: Any, k: int) -> list[Chunk]:
    """Top hits that are NOT the source chunk.

    These are hard by construction: the base retriever already thinks they are
    the best answers to this query. Teaching the cross-encoder to push them below
    the true clause is exactly the job it does at inference.
    """
    hits = retriever.search(query, k=k + 5)
    return [
        c for c, _ in hits if not (c.policy_id == source.policy_id and c.heading == source.heading)
    ][:k]


async def build(args: argparse.Namespace) -> list[Pair]:
    provider = get_provider(args.provider, args.model)
    retriever = get_retriever()
    chunks = load_corpus()
    if args.limit:
        chunks = chunks[: args.limit]

    pairs: list[Pair] = []
    kept = dropped = 0
    for i, chunk in enumerate(chunks, 1):
        try:
            queries = await generate_queries(chunk, provider, args.per_chunk)
        except Exception as exc:
            print(f"  [{i}/{len(chunks)}] {chunk.policy_id} {chunk.heading[:34]:34} FAILED: {exc}")
            continue

        good = [q for q in queries if not looks_like_the_clause(q, chunk) and not too_generic(q)]
        dropped += len(queries) - len(good)
        kept += len(good)
        print(f"  [{i}/{len(chunks)}] {chunk.policy_id} {chunk.heading[:34]:34} {len(good)} kept")

        for q in good:
            common = {
                "query": q,
                "query_policy_id": chunk.policy_id,
                "provider": provider.name,
                "model": provider.model,
                "prompt_version": PROMPT_VERSION,
            }
            pairs.append(
                Pair(
                    passage=chunk.text,
                    label=1,
                    policy_id=chunk.policy_id,
                    heading=chunk.heading,
                    **common,
                )
            )
            for neg in mine_negatives(q, chunk, retriever, args.negatives):
                pairs.append(
                    Pair(
                        passage=neg.text,
                        label=0,
                        policy_id=neg.policy_id,
                        heading=neg.heading,
                        **common,
                    )
                )

    total = kept + dropped
    rate = (100 * dropped / total) if total else 0
    print(f"\n  queries kept {kept}, dropped {dropped} ({rate:.0f}% verbatim or too generic)")
    if rate > 50:
        print("  WARNING: most output was unusable. Read the --dry-run samples before training;")
        print("  a weak generator produces a model that measures nothing.")
    return pairs


def main() -> None:
    ap = argparse.ArgumentParser(description="Build reranker training pairs from the corpus.")
    ap.add_argument("--provider", default="local", choices=KINDS)
    ap.add_argument("--model", default=None)
    ap.add_argument("--per-chunk", type=int, default=8, help="queries generated per clause")
    ap.add_argument("--negatives", type=int, default=4, help="hard negatives per query")
    ap.add_argument("--limit", type=int, default=None, help="only the first N chunks")
    ap.add_argument("--dry-run", action="store_true", help="print samples, write nothing")
    args = ap.parse_args()

    print(f"\ngenerating from {len(load_corpus())} chunks · provider={args.provider}\n")
    pairs = asyncio.run(build(args))

    if args.dry_run:
        print("\n  --- sample (nothing written) ---")
        for p in pairs[:12]:
            kind = "POS" if p.label else "neg"
            print(f"  {kind} [{p.policy_id}] {p.query}")
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as fh:
        for p in pairs:
            fh.write(json.dumps(asdict(p)) + "\n")
    pos = sum(p.label for p in pairs)
    print(f"  wrote {len(pairs)} pairs ({pos} positive, {len(pairs) - pos} negative) to {OUT}")


if __name__ == "__main__":
    main()
